default: all

PYREVERSE_PKGS = castle.TESTDOUBLES.aigr.sieve

LAST = \
	pytst/test_0_base.py			\
	pytst/test_1_sieve_protocols.py		\
	pytst/test_2_sieve_NS.py		\
#
CURRENT = \
#

TODO = \
#



TOPd=../../
include ${TOPd}Mk/comp.mk
