default: all

PYREVERSE_PKGS = castle.TESTDOUBLES.aigr.sieve

LAST = \
	pytst/test_0_dummy.py			\
#
CURRENT = \
	pytst/test_1_sieve_protocols.py		\
#

TODO = \
#



TOPd=../../
include ${TOPd}Mk/comp.mk
