default: all

PYREVERSE_PKGS = castle/TESTDOUBLES/aigr.base castle/TESTDOUBLES/aigr.sieve.basic

LAST = \
	pytst/base/test_0_base.py			\
	pytst/sieve/basic1/test_1_sieve_protocols.py	\
	pytst/sieve/basic1/test_2_sieve_NS.py		\
#
CURRENT = \
	pytst/sieve/basic1/test_3_interfaces.py		\
#

TODO = \
#



TOPd=../../
include ${TOPd}Mk/comp.mk
