default: all

# XXX read from ./setup.py ??
PYREVERSE_PKGS = castle/aigr

LAST = \
	pytst/test_3_namespaces.py			\
	pytst/test_2c_GenericProtocols.py		\
#
CURRENT = \
	pytst/test_SpecialiseGenerics.py		\
#
TODO = \
	pytst/test_0_AIGR.py				\
#

TOPd=../../
include ${TOPd}Mk/comp.mk
