default: all

# XXX read from ./setup.py ??
PYREVERSE_PKGS = castle/aigr castle/aigr.machinery

LAST = \
#
CURRENT = \
	pytst/test_4_statements.py	\
#
TODO = \
	pytst/test_3_namespaces.py			\
	pytst/machinery/test_9_todo.py			\
#

TOPd=../../
include ${TOPd}Mk/comp.mk
