[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "castle-aigr"
version = "0.0.1"
dependencies = []

[tool.setuptools.packages.find]
exclude = ["pytst*"]

[tool.setuptools.package-data]
"*" = ["py.typed", "*.pyi"]
