[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "castle-aigr"
version = "0.0.5"
dependencies = ["castle-monorail"]

[tool.setuptools.packages.find]
exclude = ["pytst*", "CastleCode", "ASIDE"]

[tool.setuptools.package-data]
"castle.aigr"       = ["py.typed", "*.pyi"]
"castle.aigr_extra" = ["py.typed", "*.pyi"]
"castle.aigr.tools.scaffolding" = ["py.typed", "*.pyi"]

[tool.pytest.ini_options]
markers = [
    "slow: marks tests as slow (use --fast to include)"
]

[tool.mypy]
namespace_packages 		= true
explicit_package_bases 	= true
python_version 			= "3.13"
mypy_path = [
   "./../../base_packages/castle-monorail",
   "./../../base_packages/castle-aigr",
   "./../../core_packages/castle-RPy-writer",
]

[tool.mutmut]
paths_to_mutate = [ "castle/" ]
tests_dir       = [ "pytst/" ]
debug = true



