[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "castle-aigr"
version = "0.0.1"
dependencies = []

[tool.setuptools.packages.find]
exclude = ["pytst*", "CastleCode", "ASIDE"]

[tool.setuptools.package-data]
"castle.aigr"       = ["py.typed", "*.pyi"]
"castle.aigr_extra" = ["py.typed"]

[tool.pytest.ini_options]
markers = [
    "slow: marks tests as slow (use --fast to include)"
]

[tool.mypy]
namespace_packages = true
explicit_package_bases = true
python_version = "3.13"