default: all

PYREVERSE_PKGS = \
	castle.aigr.tools \
	\
#
LAST =   \
	pytst/trawlers/test_1_trawl_basics.py	\
	pytst/trawlers/test_2_trawl_up.py	\
#
CURRENT = \
	pytst/trawlers/test_0_scaffolder_contract.py
#
TODO =   \
	pytst \
#

TOPd=../../
include ${TOPd}Mk/comp.mk



