default: all

PYREVERSE_PKGS = \
	castle.aigr.tools \
	\
#
LAST =   \
	pytst \
#
CURRENT = \
	pytst/trawlers/test_1_trawl_basics.py\
#
TODO =   \
	pytst/trawlers/test_2_trawl_up.py\
#

TOPd=../../
include ${TOPd}Mk/comp.mk



