# (C) Albert Mietus, 2026. CodeAI=GH.Claude.Opus-4.8
#
# Type stub (signatures + usage docs) for ``castle.aigr.expressions.operators``.
# Hand-maintained "manual autodoc" companion to operators.py.
#
# Operators are *marker* classes: an instance carries no value, only its type.
# They are grouped by associativity/arity and fed to the operator-expression
# nodes (see operator_expressions.py) and to the ``builders.build_expr`` helpers.

from .. import AIGR as AIGR

class _operator(AIGR):
    """Base of all operators (a value-less marker; the class identity is the operator)."""

class _LeftAssociative(_operator):
    """Left-associative binary operators (used by ``LRexpression``)."""
class Times(_LeftAssociative): ...
class Div(_LeftAssociative): ...
class Modulo(_LeftAssociative): ...
class Add(_LeftAssociative): ...
class Sub(_LeftAssociative): ...

class _RightAssociative(_operator):
    """Right-associative binary operators (used by ``RLexpression``)."""
class Power(_RightAssociative): ...

class _compare_op(_operator):
    """Comparison operators; cascadable as ``1 < 2 < 3`` (used by ``Compare``)."""
class Equal(_compare_op): ...
class NotEqual(_compare_op): ...
class Less(_compare_op): ...
class LessEqual(_compare_op): ...
class Greater(_compare_op): ...
class GreaterEqual(_compare_op): ...
class Is(_compare_op): ...
class IsNot(_compare_op): ...
class In(_compare_op): ...
class NotIn(_compare_op): ...

class _boolean_op(_operator):
    """Operators on boolean values."""
class _ShortCircuit(_operator):
    """Operators that stop evaluating once the result is fixed (return the last value)."""
class _bool_SC_op(_boolean_op, _ShortCircuit):
    """Short-circuiting boolean operators."""
class And(_bool_SC_op): ...
class Nand(_bool_SC_op): ...
class Or(_bool_SC_op): ...
class Nor(_bool_SC_op): ...
class Xor(_boolean_op): ...
class Xnor(_boolean_op): ...

class _unart_op(_operator):
    """Unary operators -- operate on a single value (used by ``Unaryexpression``)."""
class Not(_unart_op, _boolean_op): ...
class Negative(_unart_op): ...
class Positive(_unart_op): ...
