@startuml

skinparam packageBackgroundColor  AntiqueWhite-Gold
skinparam mapBackgroundColor      Cornsilk

package " " as p_comp <<Node>> {
   object Elemental_HelloWorld  <<ComponentImplementation>> {
   }
}

note as N1
     The impliciet ComponentInterface
     `impliciet_Main_Elemental_HelloWorld`
     is **not** shown (yet)
end note

package " " as p_m_HW <<Rectangle>>  {
   object "HelloWorld(str:label)" as HelloWorld <<Method>> {
     returns:		None
     parameters: 	str:label
     body
   }

   object " " as s11 <<VoidCall>>
   object "print()" as s12 <<Call>> {
     "Hello {label} World"
     label: ID.Ref
   }
   s11 ->s12
}

package " " as std_invoke <<Rectangle>>   {
   object "invoke() on self.std" as invoke <<EventHandler>> {
     protocol:		std
     event:		invoke
     port:		std
     body
   }

   object "Elemental" as c1 <<Constant>>
   object " " as s21 <<VoidCall>>
   object "HelloWorld" as s22 <<Call>> {
     arguments
   }
    s22 .> p_m_HW #green
   s21 ->s22
   s22::arguments -->c1
}


map "Hello_World" as ns1 <<Source_NS>> {
  source 					=> "Hello_World.Castle"
  __doc_ 					=>
  "Elemental_HelloWorld" 	*--> Elemental_HelloWorld
}

package  p_comp {
   map "Elemental_HelloWorld" as ns2 <<_hasScope>> {
      self 					=>
      std::invoke::std 		*->  invoke
      HelloWorld 			*->  HelloWorld
   }
   Elemental_HelloWorld *-> ns2
   ns1 <.* ns2: outer_ns
   note top of ns2 #lightblue: mangle_event_handler\n(proto::event:port)

}


package p_m_HW {
   map "HelloWorld" as ns3 <<_hasScope>> {
      label => str
   }
   HelloWorld *-> ns3
   ns2 <..* ns3 : outer_ns
}


package p_m_HW {
   map "statements" as  _HelloWorld_Body  #lightblue {
      1 *-> s11
   }
   HelloWorld 		*-- _HelloWorld_Body:body
}

package std_invoke {
   map "statements" as _invoke_Body #lightblue{
      1 *->s21
   }
   invoke *-- _invoke_Body:body
}




note as N2
@impliciet(<color:darkBlue>Main</color>)
<color:green>implement</color> <color:darkBlue>Elemental_HelloWorld</color>
<color:Lime>{</color>

<color:Blue>HelloWorld</color><color:Lime>(</color><color:CornflowerBlue>str</color><color:Navy><color:Lime>:</color </color><color:OliveDrab>label</color><color:Lime>)</color> <color:Lime>{</color>
   print<color:Lime>(</color><color:Sandybrown>"Hello {label} World"</color><color:Lime>)</color>
<color:Lime>}</color>

<color:Blue>invoke</color>() <color:green>on</color> self.std <color:Lime>{</color> <color:Orchid>///GAM: Here it starts ...</color>
   HelloWorld<color:Lime>(</color><color:Sandybrown>"Elemental"</color><color:Lime>)</color>
<color:Lime>}</color>

<color:Lime>}</color> <color:Orchid>/* Elemental_HelloWorld */</color>
end note
'<color:RED>
@enduml
