@startuml

object Elemental_HelloWorld  <<ComponentImplementation>> {
}
map "Hello_World" as ns1 <<Source_NS>> #Cornsilk {
  source 					=> "Hello_World.Castle"
  __doc_ 					=>
  "Elemental_HelloWorld" 	*--> Elemental_HelloWorld
}


object HelloWorld <<Method>> {
  returns:		None
  parameters: 	str:label
  body
}


together {
	object " " as s11 <<VoidCall>>
    object "print()" as s12 <<Call>> {
	  "Hello {label} World"
	  label: ID.Ref
	}
	s11 ->s12
}
together {
	map "statements" as  _HelloWorld_Body  #lightblue {
	 1 *-> s11
	}
    HelloWorld 		*-- _HelloWorld_Body: body
}


object "powerOn(max) on self.power" as powerOn <<EventHandler>> {
  protocol:		Power
  event:		powerOn
  port:		power
  parameters:	max:int
  body
}

object "Elemental" as c1 <<Constant>>
object " " as s21 <<VoidCall>>
object "HelloWorld" as s22 <<Call>> {
  arguments
}
s22::arguments -->c1

s21 ->s22
s22 ..> HelloWorld #green: <color:blue>NS:Elemental_HelloWorld


map "statements" as _powerOn_Body #lightblue{
1 *->s21
}
powerOn 		*-- _powerOn_Body :body



map "Elemental_HelloWorld" as ns2 <<NamedSpace>> #Cornsilk {
    self 					=>
    Power::powerOn::power 	*->  powerOn
    HelloWorld 				*->  HelloWorld
}
Elemental_HelloWorld *-> ns2

map "HelloWorld" as ns3 << Scope>> #Cornsilk {
}
HelloWorld *-> ns3


map "Power::powerOn::power" as ns4 <<Scope>> #Cornsilk {
}
powerOn *-> ns4

ns2 *... ns4 #red: outher
ns2 *... ns3 #red: outher
}
@enduml
