[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "castle-RPy-writer"
version = "0.0.1"
dependencies = ["castle-aigr"]

[tool.setuptools]
packages = [ # manyally maintain this
    "castle.writers.RPy",
    "castle.writers.RPy_buildin",
]

[tool.setuptools.package-data]
"castle.writers.RPy" = ["py.typed"]

[tool.pytest.ini_options]
markers = [
    "slow: marks tests as slow (use --fast to include)"
]

[tool.mypy]
namespace_packages      = true
explicit_package_bases  = true
python_version          = "3.13"
mypy_path = [
   "./../../base_packages/castle-monorail",
   "./../../base_packages/castle-aigr",
   "./../../core_packages/castle-RPy-writer",
   "./../../TestDoubles_packages/TestDoubles-HelloWorlds",
]

[tool.mutmut]
paths_to_mutate = [ "castle/" ]
tests_dir       = [ "pytst/" ]
debug = true
