[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "castle-RPy-writer"
version = "0.0.1"
dependencies = ["castle-aigr"]

[tool.setuptools]
packages = [ # manyally maintain this
    "castle.writers.RPy",
]

[tool.setuptools.package-data]
"castle.aigr" = ["py.typed", "*.pyi"]
"castle.aigr_extra" = ["py.typed"]
"castle.writers.RPy" = ["py.typed"]
"castle.TESTDOUBLES.aigr.sieve" = ["py.typed"]
"castle.TESTDOUBLES.aigr.base" = ["py.typed"]
"castle.TESTDOUBLES.aigr.HelloWorlds.elemental" = ["py.typed"]

[tool.pytest.ini_options]
markers = [
    "slow: marks tests as slow (use --fast to include)"
]

[tool.mypy]
namespace_packages = true
explicit_package_bases = true
