[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "castle-RPy-writer"
version = "0.0.1"
dependencies = ["castle-aigr"]

[tool.setuptools.packages.find]
exclude = ["pytst*"]
