# (C) Albert Mietus, 2025. Part of Castle/CCastle project

import typing as PTH                                                                                  # Python TypeHints
from dataclasses import dataclass, KW_ONLY

from castle.aigr import namespaces, NamedNode

@dataclass
class RPy_file(NamedNode, namespaces._Target_NS):
    """This namespace represents a (one) file that is (will be) generated by the RPy-writer

    This ``_NameSpace`` is has a name, maily for debug/log purposes. This name comes from the NamedNode-mixin"""

    def write_out(self, dir=None):
        assert False, f'ToDo {self.__class__}::write_out'
        txt = self._render()
        self.save(txt, dir)

    def save(self, txt, dir=None):
        assert False, f'ToDo {self.__class__}::save'

    def _render(self, renderer=None) ->str:
        assert False, f'ToDo {self.__class__}::_render//self.renderer'
        if not renderer:
            renderer=self.renderer
        txt = renderer.render(self)
        return txt
