# (C) Albert Mietus, 2025. Part of Castle/CCastle project

import typing as PTH                                                                                  # Python TypeHints
from dataclasses import dataclass, KW_ONLY

from castle.aigr import namespaces

@dataclass
class RPy_file(namespaces._Target_NS):
    """This namespace represents a (one) file that is (will be) generated by the RPy-writer"""

