default: all

PYREVERSE_PKGS = \
	castle.TESTDOUBLES.aigr.HelloWorlds.elemental	\
#

LAST = \
	pytst/d1_elemental/		\
#
CURRENT = \
	pytst/d2_credible/		\
#
TODO = \
	pytst/	\
#



TOPd=../../
include ${TOPd}Mk/comp.mk
