default: all

PYREVERSE_PKGS = \
	castle.TESTDOUBLES.aigr.HelloWorlds.elemental	\
#

LAST = \

#
CURRENT = \
	pytst/elemental/test_1_elementalHW_base.py
#

TODO = \
#



TOPd=../../
include ${TOPd}Mk/comp.mk
