default: all

PYREVERSE_PKGS = \
	castle.TESTDOUBLES.aigr.HelloWorlds.elemental	\
#

LAST = \
	pytst/elemental/test_1_elementalHW_base.py		\
#
CURRENT = \
	pytst/elemental/test_1_elementalHW_base.py		\
#

TODO = \
	pytst/elemental/test_2_impliciet.py				\
#



TOPd=../../
include ${TOPd}Mk/comp.mk
