[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "castle-TestDoubles-HelloWorlds"
description = "A (partial, manually crafted) ``aigr`` TestDouble(s) for Sieve(s) -- as ref for reading(parsing) or input for writing"
version = "0.0.2"
dependencies = ["castle-aigr",]

[tool.setuptools.packages.find]
exclude = ["pytst*", "ASIDE"]

[tool.setuptools.package-data]
"*" = ["py.typed", "*.pyi", "CastleCode/**/*.Castle"]

[tool.pytest.ini_options]
markers = [
    "slow: marks tests as slow (use --fast to include)"
]
[tool.mypy]
namespace_packages      = true
explicit_package_bases  = true
python_version 			= "3.13"
mypy_path = [
   "./../../base_packages/castle-monorail",
   "./../../base_packages/castle-aigr",
   "./../../core_packages/castle-RPy-writer",
]


