[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "castle-TestDoubles-aigr-base"
description = "Manually crafted ``aigr-aigr``, as TestDouble for other TestDoubles"
version = "0.0.1"
dependencies = ["castle-aigr"]

[tool.setuptools.packages.find]
exclude = ["pytst*", "CastleCode", "ASIDE"]

[tool.setuptools.package-data]
"*" = ["py.typed", "*.pyi"]

[tool.pytest.ini_options]
markers = [
    "slow: marks tests as slow (use --fast to include)"
]

[tool.mypy]
namespace_packages = true
explicit_package_bases = true
 
