@startuml


package Classes <<Cloud>> {
class ComponentInterface
}



'SieveMoat = ComponentInterface(name=ID("Sieve"),
'                                   ports=(
'                                       Port(name='try',     direction=PortDirection.In,  type=protocols.SimpleSieve),
'                                       Port(name='coprime', direction=PortDirection.Out, type=protocols.SimpleSieve),
'                                       ))
object SieveMoat {
  name = "Sieve"
  ports = [try, coprime]
}
ComponentInterface <|-- SieveMoat

@enduml
