default: all


PYREVERSE_PKGS = \
	castle.readers \
	\
	castle.readers.parser \

#
LAST = \
	pytst/bootstrap/test_0a_bootstrap-tatsu.py \
	pytst/bootstrap/test_0b_bootstrap-tatsu_dict.py\
	pytst/parse/test_1b_parms.py \
	pytst/parse/test_1a_names.py \
#
CURRENT = \

#
TODO = \
	pytst/parse/test_2a_comp_implement.py::test_3a_Comp_with_empty_EH\
	pytst/parse/test_2a_comp_implement.py\
#




TOPd=../../
include ${TOPd}Mk/comp.mk

