default: all


PYREVERSE_PKGS = \
	castle.readers \
	castle.readers.parser \
#
LAST = \
	pytst/parse/test_1b_parms.py \
	pytst/parse/test_1a_names.py \
#
CURRENT = \
	pytst/parse/test_2a_proto.py\
	pytst/parse/test_3_comp_interface.py -k test_2_ComponentWith2Ports
#
TODO = \
	pytst/parse/test_9a_comp_implement.py::test_3a_Comp_with_empty_EH\
	pytst/parse/test_9a_comp_implement.py\
#


TOPd=../../
include ${TOPd}Mk/comp.mk

