# (C) Albert Mietus, 2025. Part of Castle/CCastle project

import logging; logger = logging.getLogger(__name__)

import typing as PTH                                                                                  # Python TypeHints
from dataclasses import dataclass, KW_ONLY
from pathlib import Path

from castle.aigr import namespaces, NamedNode

@dataclass
class RPy_unit(NamedNode, namespaces._Target_NS):
    """This namespace represents a (one) file that is (will be) generated by the RPy-writer

    This namespace has a name --mainly for debug/log purposes-- by using the NamedNode-mixin"""

    def write_out(self, dir):
        assert False, f'ToDo {self.__class__}::write_out'
        txt = self._render()
        self.save(txt, dir)

    def save(self, txt, dir):
        logger.info('%s.save(txt=%s..., dir=%s) file:=%s', self.__class__.__name__, txt[:7], dir, self.target_file)

        out_file= Path(dir) / self.target_file
        out_file.write_text(txt)

    def _render(self, renderer=None) ->str:
        assert False, f'ToDo {self.__class__}::_render//self.renderer'
        if not renderer:
            renderer=self.renderer
        txt = renderer.render(self)
        return txt
