@startuml

package Classes <<Cloud>> {
class NameSpace
class Source_NS
NameSpace <|- Source_NS
}

package NameSpaces <<Node>> {
object top {
  name="The Sieve"
}
object start_sieve
object slow_start
object simple_sieve
object base
}

package "Sieve Protocols" {
  object StartSieve
  object SlowStart
  object SlowStart_1
  SlowStart <|.. SlowStart_1
  object SimpleSieve
}
start_sieve  o.. base : register
slow_start   o.. base : register
simple_sieve o.. base : register


start_sieve  o.. StartSieve   : register

slow_start   o.. SlowStart_1  : register
simple_sieve o.. slow_start   : register

simple_sieve o.. SimpleSieve  : register

top o.. start_sieve  : register
top o..	slow_start   : register
top o..	simple_sieve : register
top o..	base         : register

@enduml
