default: all

PYREVERSE_PKGS = castle.monorail

LAST = \
	pytst/base/visitors/test_mistakes.py\
	pytst/base/visitors/test_find.py
#
CURRENT = \
	pytst/base/visitors/test_dispatch_on.py \

#
TODO = \
#

TOPd=../../
include ${TOPd}Mk/comp.mk
