[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "castle-monorail"
version = "0.0.1"
dependencies = []

[tool.setuptools.packages.find]
exclude = ["pytst*", "CastleCode", "ASIDE"]

[tool.setuptools.package-data]
"castle.monorail"       = ["py.typed", "*.pyi"]
#"castle.monorail.base"  = ["py.typed", "*.pyi"]

[tool.pytest.ini_options]
markers = [
    "slow: marks tests as slow (use --fast to include)"
]

[tool.mypy]
namespace_packages 		= true
explicit_package_bases 	= true
python_version 			= "3.13"
mypy_path = [
   "./../../base_packages/castle-monorail",
   "./../../base_packages/castle-aigr",
   "./../../core_packages/castle-RPy-writer",
]

[tool.mutmut]
paths_to_mutate = [ "castle/" ]
tests_dir       = [ "pytst/" ]



